bootstrap-ruby/bootstrap_form

- lib/bootstrap_form/form_builder.rb
The wrapper options must be retrieved from css_options to work for every control and it must be merged (instead of reverse_merged) because empty form_group_options values prevent a reverse_merge to work (and if we specify things in wrapper, they should always be considered as more important than default options).
Fix #153
> Fix wrapper options

- lib/bootstrap_form/form_builder.rb
Since ActiveRecord constant is undefined on configs with alternate ORMs,
we first need to check if that value is available before evaluating it.
[bootstrap-ruby/rails-bootstrap-forms#189]
> Fix breaks on non-ActiveRecord setups

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_radio_button_test.rb
Allow :value_method and :text_method for collection_check_boxes and collection_radio_buttons to be any Object that responds to , e.g. a Proc or lambda, to match the same functionality as provided by the corresponding Rails form helper methods.
Ensure that a single String checked value does not perform an include? check by converting checked value(s) to an Array.
> Allow callable value_method and text_method for collection_check_boxes and collection_radio_buttons

- CHANGELOG.md
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_other_components_test.rb
Hi,
Primary button classes aren't overridden when you pass classes as the option.
```ruby
= post.primary 'create', class: 'btn btn-primary disabled' # disabled class is ignored!!
```
That's becase [Hash#merge use other_hash's value](http://www.ruby-doc.org/core-2.1.5/Hash.html#method-i-merge).
```ruby
options = { class: 'btn btn-primary disabled ' }
options.merge! class: 'btn btn-primary' #=> {:class=>"btn btn-primary"}
```
[ActiveSupport's reverse_merge](http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html#method-i-reverse_merge) takes care of this problem.
```ruby
options = { class: 'btn btn-primary disabled ' }
options.reverse_merge! class: 'btn btn-primary' #=> {:class=>"btn btn-primary disabled"}
```
Thanks.
> Can't override primary button's classes

- Gemfile.lock
- lib/bootstrap_form/form_builder.rb
Though this gem helpers don't use native collection helpers, they have name collision, so it was impossible to use native helpers with bootstrap form.
> allow to use native collection check_box/radio helpers

- lib/bootstrap_form/form_builder.rb
Fix an issue that causes bootstrap form builder to crash when a field is assigned to a Ransack Search Class, by no longer assuming the object always responds to `on_validators` while figuring out whether the field is required.
> Fix a crash when using form for Ransack

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
When generating fields, it should be possible to specify a hash in the
format of `label: { text: "A label", class: "a-class" }`, as indicated
in the documentation.
This approach assumes that if the developer has specified the label as a
hash, then it trumps `label_class` in the options hash.
> Allow label options to be passed in as a hash

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_selects_test.rb
Beginning with Rails 4.1.0, the select method allows to pass a block to
render as the options string:
http://apidock.com/rails/v4.1.8/ActionView/Helpers/FormOptionsHelper/select
(the link points to 4.1.8, but it is the same for 4.1.0)
Adapt the gem to allow this.
The test is marked to run on Rails >= 4.1.0 only.
One problem remains though: When updating Rails to 4.1.0 in test
environment, many other tests fail because the order of attributes in
the output changed. I don't know how to solve this yet without rewriting
the expected output for different Rails versions (wich is a cumbersome
task ...).
> Allow to pass block to select helper in Rails >= 4.1.0

- CHANGELOG.md
- lib/bootstrap_form/aliasing.rb
- lib/bootstrap_form/form_builder.rb
In Rails 5, `alias_method_chain` is deprecated in favor of `Module.prepend`. However, `prepend` is only available in Ruby 2.0+, and we still want to support Ruby 1.9.
Furthermore, the `*_without_bootstrap` aliases that `alias_method_chain` creates are genuinely useful for users of bootstrap_form, because there are some cases where you don't want the Bootstrap-specific markup.
Essentially, we want the traditional `alias_method_chain` behavior, but without the pesky deprecation warnings. This commit reimplements `alias_method_chain` under a new name, `bootstrap_method_alias`. This allows us to keep the behavior the same and avoid the deprecation warnings.
Fixes #253.
> Fix alias_method_chain deprecation messages in Rails 5

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
Currently the `#form_group` method attempts to mutate the
`:control_col` option if no label is supplied. Since this option is
passed by the user, it may be a frozen string literal. Instead, we
simply avoid mutating the supplied string.
As we approach Ruby 3 and frozen string literals become more common,
this is more likely to fail.
*edit: updated changelog.
> Prevent mutating (possibly) frozen strings

- Gemfile.lock
- bootstrap_form.gemspec
This should fix a bundler error in the Travis build.
> Pin mime-types version for Ruby 1.9 compatibility

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
Fixes mismatching `<label>` `for` and `<input>` `id`.
rails-bootstrap-forms delegates generating the `<input>` `id` to Rails, but generates <label> `for` itself. Because we were not sanitizing the value we use for `<label>` `for`, we get a mismatch between the two, when, for example, the checkbox value has a space in it. This is a a11y problem because browsers do not connect a `<label>` with an inner `<input>` if the label has a `for` that doesn't match the inner `<input>`'s `id`.
> Sanitize our <label> `for` in accordance with Rails' <input> `id`

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
Added `skip_required` as a field option to prevent the usual checks
for a PresenceValidator and the addition of a 'required' CSS class
to the label element.
This is a fix for #205 and builds on the work done in #143.
(was:)
> Added new field option `label_required` that, if present, will control
> whether the `required` CSS class is added to the label element. If not
> present, continue to use the existing logic that looks for a
> PresenceValidator on the model object.
> Allow manual control of label 'required' class

- CHANGELOG.md
- lib/bootstrap_form.rb
this prevents errors with load order of helpers when using rspec for tests.
I also think this should be the way to go for loading extensions.
This is small part of the changes from my previous PR #269
> hook include of helper to loading of ActionView

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/special_form_class_models_test.rb
taken from https://github.com/bootstrap-ruby/rails-bootstrap-forms/pull/217 (@boffbowsh)
Relying on Class#name for model naming breaks compatibility with
anonymous models. The ActiveModel::Naming#model_name method is
preferred
Also, don’t attempt to get help text for nil objects. This was
previously attempting to lookup activerecord.help.nil_class.field_name or similar.
> Don't rely on Class#name for model naming

- test/dummy/config/boot.rb
To suppress the following warning from Ruby:
```
warning: File.exists? is a deprecated name, use File.exist? instead
```
`File.exist?` is defined in current supported Ruby versions.
> Use `File.exist?` instead of `File.exists?`

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/dummy/app/models/faux_user.rb
- test/special_form_class_models_test.rb
This is useful in using Bootstrap Forms with third party libraries such as Ransack, whose queries and values do not always conform fully to the Active Model API.
A class's name, while model_name is preferred, is still a good fallback.
> Support form objects that lack model names

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_test.rb
When building horizontal forms with a label_col other than col-sm-*, the offset would be calculated incorrectly. I changed the method offset_col to take other column breakers into account.
> Fix offset_col to match label with for non-sm column classes

- CHANGELOG.md
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_other_components_test.rb
`static_control` wraps the displayed value in a `p` tag.
This is a problem in some edge use case, when you want to display an `ul` element.
It leads to invalid HTML generation that is silently changed by erb / haml / slim.
This view (slim) :
```
= f.static_control(:my_attribute) do
ul
li abc
li def
```
Generate something like :
```
...
<p></p>
<ul><li>abc</li><li>def</li><ul>
<p></p>
...
```
The new `custom_control` helper generates expected view :
```
...
<p>
<ul><li>abc</li><li>def</li><ul>
</p>
...
```
> add custom_control

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_selects_test.rb
> Support :prepend and :append for the `select` helper

- .travis.yml
by disabling sudo we allow travis to run the build in a container environment, which is expected to be much quicker.
> let travis use container builds

- .travis.yml
- Appraisals
- gemfiles/4.0.gemfile
- gemfiles/4.1.gemfile
- gemfiles/4.2.gemfile
- gemfiles/5.0.gemfile
- gemfiles/5.1.gemfile
- test/bootstrap_form_test.rb
- test/dummy/config/initializers/generic_migration.rb
- test/dummy/db/migrate/20130703191909_create_users.rb
- test/dummy/db/migrate/20130703191937_create_addresses.rb
- test/dummy/db/migrate/20130912171202_add_preferences_to_user.rb
- test/dummy/db/migrate/20140327190145_add_terms_to_user.rb
- test/dummy/db/migrate/20140922133133_add_type_to_users.rb
- test/dummy/db/schema.rb
The start of fixing #329
defining a gem as `~> 5.0` would allow bundler to install `5.1`, which is not what we want, and made the build fail all of a sudden. So I updated it to use more explicit version definitions.
Also added 5.1, which is still failing, but that will be step 2.
> add 5.1, use more explicit version definition for existing

- README.md
The `legacy-2.7` branch supports Bootstrap v3, not v4. Add a prominent message to make that clear.
> Clarify Bootstrap v3 support in 2.7.x README

- README.md
The master branch is now targeting Bootstrap v4, Rails 5+, and Ruby 2.3+. Make it clear that the master branch is not yet stable, and refer people to the `legacy-2.7` branch for Bootstrap v3 support.
> Update README to explain new Ruby, Rails, Bootstrap requirements

- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_selects_test.rb
Beta 3 introduced a breaking change with how input group addons
are used with prepend and append. Details can be found here in
their migration docs:
https://getbootstrap.com/docs/4.0/migration/#input-groups
> Fix Bootstrap v4.0.0-beta.3 breaking change with input group addons

- README.md
Fixing error reported on https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/351
> fix typo on select usage example

- Gemfile
Minitest 5.11 is broken for environments, like Rails, that use custom reporters. Pin to 5.10.3 in the meantime.
Addresses issue #371.
> Pin Minitest to work around crash on test failure.

- Gemfile
- test/gemfiles/5.0.gemfile
- test/gemfiles/5.1.gemfile
- test/gemfiles/5.2.gemfile
test gemspecs for rails < 5.2 will have it pinned permanently
> Putting minitest dependency in the right place. Fixing PR#372

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_selects_test.rb
Since we don't care about Rails 3 and 4 we don't need those checks (not like any of that stuff was tested anyways)
> [v4] Removing old Rails checks

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_selects_test.rb
- test/special_form_class_models_test.rb
Check if any classes actually make it through to the label, so we don't generate a useless `class=""` on the label. Fixing this fixes a lot of `form_with` test cases that haven't yet been merged.
Fixes #382.
> Don't add class="" to label if no classes specified.

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
`check_boxes_collection` and `radio_buttons_collection` are gone for a long time now.
> [v4] Removing deprecated methods

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
Glyphicons are not part of Bootstrap4 and markup generated is not a thing anymore.
> [v4] Removing glyphicon option

- test/bootstrap_form_group_test.rb
Addresses #397 and unblocks #379.
All other test cases in the same file that used the `@horizontal_form_builder` have class `col-form-label` on the `label` in the expected string, but the test at line 403 of `test/bootstrap_form_group_test.rb` didn't.
@mattbrictson could you please look at this closely, and make sure it was correct to simply change the expected string in the test case?
> Fix expected string for one horizontal form test case.

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_fields_test.rb
Latest (beta3) version of bootstrap 4 requires file input to have `form-control-file` class. This PR adds this class.
> [v4] Fix file input class

- test/bootstrap_form_test.rb
I found another instance of the `<div style="margin:0;padding:0;display:inline">` in a test case. How did it stay hidden so long? Then the same test case started failing with what turned out to be an extra `</div>`.
I ended up re-organizing the production of the expected string to remove some redundancy and hopefully make it clearer what the differences are.
Again, please review this closely. It doesn't feel right to just be changing expected strings in the test cases.
Is it possible that since @GBH fixed `assert_equivalent_xml`, we're now encountering cases where the test was always broken, but we didn't know it because `assert_equivalent_xml` wasn't working?
> Remove legacy markup.

- .gitignore
- CHANGELOG.md
- Dangerfile
- README.md
- bootstrap_form.gemspec
- test/gemfiles/5.1.gemfile
- test/gemfiles/5.2.gemfile
This PR includes a handful of tweaks:
1. Fix a mistake in Ruby version requirement listed in the README: we support 2.2.2+, not 2.3+.
2. Using the various gemfiles in `test/gemfiles` causes `.lock` files to be created. These should never be committed, so add them to the `.gitignore`.
3. The repo URL has recently changed; update the homepage in the gemspec to match.
4. The minitest fix in Rails has been backported to the 5.1 branch; add a comment as a reminder to remove our workaround once 5.1.5 has been released.
5. The CHANGELOG did not explain the magnitude of the changes since the last bootstrap_form release (2.7.0) and there are too many markup changes to reasonably list. Rewrite the CHANGELOG to explain what has changed at a high-level and direct people to the Bootstrap v4 docs for a …
> Miscellaneous cleanup; rewrite CHANGELOG for 4.0.0

- test/test_helper.rb
Thanks to @mattbrictson for figuring this out. I just implemented what he suggested. :-)
This PR doesn't affect end users. It simply pretty-prints output from failed tests, so that it's easier to see where the differences are.
> Pretty-print output of failed tests #399.

- test/test_helper.rb
Once demo app is used, then subsequent runs of `rake test` would print an `EnvironmentMismatchError`. Removing the `RAILS_ENV=test` assignment fixes this warning.
Fixes #402
> Fix EnvironmentMismatchError when running tests

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
This also fixes the broken Travis build status badge in the README.
> Update URLs to match the new repo name

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_selects_test.rb
If provided, use html option `id` to specify `for` attribute on label
for (text, email...) fields, checkbox, radio and select.
Solves #213, #221, #342, #349 issues and supercede #221 and #343 pull
requests.
Partially solves #251 (only the part regarding the `id`.
> Use option[:id] for label's *for* attribute

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_radio_button_test.rb
Bootstrap 4 no longer wraps radio buttons and check boxes inside the label. Previously it was:
```
<div class="form-check">
<label class="form-check-label" for="user_misc_1">
<input class="form-check-input" type="checkbox" value="1" name="user[misc][]" id="user_misc_1" />
Foo
</label>
</div>
<div class="radio">
<label for="user_misc_1">
<input type="radio" value="1" name="user[misc]" id="user_misc_1" />
Foo
</label>
</div>
```
Where it should be:
```
<div class="form-check">
<input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
<label class="form-check-label" for="defaultCheck1">
Default checkbox
</label>
</div>
<div class="form-check">
<input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
<label …
```
> Render Bootstrap 4 Radio Buttons and Check Boxes

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_radio_button_test.rb
Use the correct Bootstrap 4 classes for radio buttons.
This PR corrects the classes on inline radio buttons, but does not address the overall format (wrapping) of inline radio buttons for Bootstrap 4. That will be in a separate PR.
There is some redundancy in this code, because I chose to try to minimize changes to achieve the desired functionality, rather than refactor to the DRYest state. I expect that the code will naturally get DRYer in the next PR, and that any remaining DRYing up can be handled by a separate PR later.
This is part of the work for #395.
> Use Bootstrap 4 radio button classes.

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_radio_button_test.rb
The Bootstrap 4 tags for radio buttons and check boxes is more regular, so the helpers are somewhat shorter, at the cost of perhaps making the review more difficult.
If there's a way to show the diff without comparing white space, it might give you a better idea of the real changes, most notably in the test cases.
This PR partially addresses #395.
> Handle inline radio buttons and check boxes for Bootstrap 4.

- README.md
Update the README to match changes from issue #395. There are a few examples of rendered output in the README that included check boxes, which have changed for Bootstrap 4.
> Update the README to match changes from issue #395

- CHANGELOG.md
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_test.rb
- test/bootstrap_other_components_test.rb
> Add option[:id] on static control #245

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_radio_button_test.rb
This PR updates markup for check boxes and radio buttons to Bootstrap 4. It applies to the `radio` and `check_box` helpers only, not the `collection_radio_buttons` and `collection_check_boxes`. The collection versions should probably be discussed under #412.
Further clean-up of this code is possible, but an attempt was made to minimize changes (not always successful, mind you).
This is part of the response to #395.
> Update `hide_label` and `skip_label` for check boxes and radio buttons

- test/bootstrap_fields_test.rb
Add a test that proves we don't need a `fields_with_bootstrap` method. 
Fixes #427.
> Add test to prove #427 is *not* an issue.

- test/bootstrap_fields_test.rb
- test/bootstrap_selects_test.rb
This pull request adds tests for various controls when there is an validation failure on the control. All these tests document the behaviour of the master branch as of the time the PR was created. 
Bootstrap 4's handling of errors is different that Bootstrap 3's, and has led to some issues already, e.g. #417 and #395. The tests here, therefore, document current functionality, so they give us a baseline for any required changes. These tests should not be considered a declaration about how `bootstrap_form` should render errors with Bootstrap 4. 
These tests also provide more coverage to ensure we don't introduce regressions as we address #417, #395 and any other issues that come up.
Given this PR contains only a few tests which don't significantly increase the run time of the test suite, I …
> Test the rendering of errors for various controls.

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
Bootstrap 4 has different [offset classes](https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns). This PR changes test cases and changes the method that generates the offset class.
Fixes #425.
> Bootstrap 4 offset classes.

- README.md
Bootstrap 4 makes it challenging to override form-level `layout: :inline`. This PR just documents that you can't do it.
@mattbrictson you agreed to this in https://github.com/bootstrap-ruby/bootstrap_form/issues/432#issuecomment-366471106, so approval should be easy.
Fixes #432.
> Clarify overriding layouts [skip ci].

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_fields_test.rb
This is a rebase and redo of #306 by @trammel.
I did the minimum necessary (I think) to generate the appropriate markup [explained in the v4 docs](http://getbootstrap.com/docs/4.0/components/forms/#file-browser).
```html
<div class="form-group">
<label for="user_misc">Misc</label>
<div class="custom-file">
<input class="custom-file-input" id="user_misc" name="user[misc]" type="file" />
<label class="custom-file-label" for="user_misc">Choose file</label>
</div>
</div>
```
Note that in Bootstrap v4:
> We hide the default file `<input>` via opacity and instead style the `<label>`.
In other words, the `label.custom-file-label` is styled to look like a text input, and the contents of that label are used for the placeholder text inside that pseudo-text input. The placeholder is "Choose file" by …
> Bootstrap v4 file input

- lib/bootstrap_form/form_builder.rb
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_group_test.rb
The help text and error message are no longer rendered in the same
place. The help text is now rendered in the `form-group` div instead
of in the `input-group` div. Before we could render the error and help
text together, however that has changed and they need to be separate.
With this separation we need to check in the `generate_help` method to
see if there are errors and if inline errors are being rendered; as we
don't want to render the help text then.
Note - 
At first it seemed a little strange that the help text is not being rendered in the event of an error. It does seem to make sense and look better if they aren't both rendered at the same time. I don't know if I'd want to render them both at the same time ever, but I'm curious of others might. They could make the failing …
> Issue #444 - Help text rendered in wrong place.

- CHANGELOG.md
- README.md
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_other_components_test.rb
In Bootstrap 4 the `form-control-static` class no longer exists. It
has been replaced with using the `form-control-plaintext` class on a
readonly input. This reflects that change in approach.
There are a couple of potential problems/oddities.
From a backwards-compatabilty standpoint, if people have been putting
other tags inside of the block this will likely break whatever they
may have been trying to do. There doesn't seem to be any way around
this limitation as it is caused by the text input approach.
Secondly, this approach seems to break convention in this project a
little. It doesn't seem as if any of the `_with_bootstrap` methods are
directly referenced anywhere. I'm not sure how much of a problem this
is, it seemed like the best way to stay DRY.
Should I also update the CHANGELOG? …
> Fixes #443 - Updates `static_control` method.

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
This adds support for help text using :html subkey instead of the "_html" suffix to the attribute name.
Both are supported by i18n, actually: http://guides.rubyonrails.org/i18n.html#using-safe-html-translations .
This code just makes an additional check for an html subkey. If none is found, it continues in the regular fashion.
> Support for i18n :html subkeys in help text

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
When using horizontal forms the help text is placed inside the created row but as sibling of the cols for label and control. This codechange moves the help text inside the col of the control so it gets aligned with/under the control.
Before:
After:
> Moves help text in horiz. forms under the control

- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_test.rb
This maintains the appearance of label errors consistent with v2.7 (Bootstrap 3).
With Bootstrap 4's way of marking up validation errors, the label text with a label error was not displaying in the error colour (default red). This PR adds `.text-danger` to a label when `label_errors: true` and there is a validation error on the field.
`invalid-feedback` was rejected as it changes the font appearance, and also doesn't appear to display, even though it's a sibling of the `input.is-invalid`. It looks like `.text-danger` is always the colour of validation errors, unless the programmer is doing some really interesting customization of Bootstrap colours.
No issue was entered for this as the fix was so quick. (My bad.)
> Add text-danger to label when label_errors: true

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
Fixed a problem that `FormBuilder#check_box_with_bootstrap` https://github.com/bootstrap-ruby/bootstrap_form/blob/master/lib/bootstrap_form/form_builder.rb#L140 will remove any non-English letters passed in as the `for` attribute for the label tag. Therefore any group of checkboxes contains non-English values won't work.
> Fix label `for` attribute when passing non-english characters using `collection_check_boxes`

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
Per #332 this PR will add support for a `label_as_placeholder` option allowing you to add the field title to an input fields `placeholder` attribute and hiding the label simultaneously.
> Add support for `label_as_placeholder` option

- test/test_helper.rb
Fixes 2 issues:
```
`require': `require 'mocha/mini_test'` has been deprecated. Please use `require 'mocha/minitest' instead.
```
and
```
BootstrapFormGroupTest#test_help_messages_to_warn_about_deprecated_I18n_key:
Mocha::NotInitializedError: Mocha methods cannot be used outside the context of a test
```
> Ensure tests work with mocha 1.5.0

- CHANGELOG.md
- UPGRADE-4.0.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
In Bootstrap 3, `.form-group` mixed in `.row`. In Bootstrap 4, it doesn't. So `bootstrap_form` automatically adds `.row` to the `div.form-group`s that it creates, if the form group is in a horizontal layout.
Bootstrap 4 provides a `.form-row`, which has smaller gutters than `.row`. If the programmer specifies ".form-row", `bootstrap_form` will replace `.row` with `.form-row` on the `div.form-group` on horizontal forms.
`UPGRADE-4.0.md` only mentions changes from this PR, assuming that the complete version of  `UPGRADE-4.0.md` will be merged from PR #448.
Fixes #449.
> Allow .form-row to replace .row in div.form-group.

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_other_components_test.rb
As the title says, this PR allows devs to render submit buttons as HTML buttons, instead of using input tags.
The major advantage of this is that these submit buttons can then be styled, because they can have HTML content, as well as support for CSS pseudo-selectors.
All existing code should keep working normally. To use buttons instead of input tags, provide the `render_as_button` option with a truthy value:
`<%= f.primary t('.signin_button'), render_as_button: true %>`
Cheers!
> Allow rendering of form submit buttons as HTML buttons, instead of input

- README.md
- test/bootstrap_checkbox_test.rb
- test/bootstrap_radio_button_test.rb
Some third-party plugins require an empty but visible label on controls. Since `hide_label` makes the label invisible, another solution is required.
Since this seems like an edge case, rather than add another option, this PR proposes a documentation change to show how to generate an empty, visible label.
Test cases were added to confirm the functionality, but are not really required as this is a documentation-only change.
Fixes #457.
> Document how to generate empty label.

- test/test_helper.rb
Setting the RAILS_ENV to `test` ensures that the Rails test setup happens as expected, loading the schema into the test database before the tests are run. This fixes a problem where the tests would fail with this message if `bundle exec rake test` is run on a fresh checkout:
ActiveRecord::StatementInvalid:  Could not find table 'users'
This is an alternative to the documentation change proposed in #462.
Note that `ENV['RAILS_ENV'] = 'test'` was originally removed by me in #403 to fix bug #402. I re-tested that scenario after making the change in this PR, and could not reproduce the original bug. So it appears it is perfectly safe to add the code back in.
> Fix "Could not find table 'users'" during tests

- Gemfile
- RELEASING.md
- Rakefile
Releasing to rubygems.org is as simple as `rake release`, but there are some additional steps around it to make sure our documentation is up to date, which I've documented in `RELEASING.md`. This is the process I used to recently publish 4.0.0.alpha1.
I've also added the `chandler` gem (my own creation) that automatically updates the GitHub Releases whenever we run `rake release`. This ensures that people can find our release notes easily. I use it on other gems I maintain, like `sshkit` and `capistrano`.
> Document the gem release process; add chandler

- test/gemfiles/5.1.gemfile
- test/gemfiles/5.2.gemfile
The Rails incompatibilities with minitest have been fixed in the most recent Rails releases. We therefore no longer need to pin to an old version of minitest as a workaround.
> Remove minitest workarounds that are no longer needed

- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_other_components_test.rb
This pull request allows one to force a nil value with static_control.
class Model
def attr
1
end
end
f.static_control :attr, value: nil
> allow static_control to force a nil value

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_test.rb
Make sure multiple label widths are converted into offsets for form groups without labels in horizontal forms.
Fixes #478
> Fix offset for form group without label when multiple label widths are specified.

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_selects_test.rb
can also override this behavior with skip_inline: true
> default form-inline class applied to parent content div on date select helpers

- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_test.rb
When there are no errors the div with for the error messages was still rendered, making it impossible to use css to style that surrounding div.
> error_summary: don't render surrounding div if there are errors

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_radio_button_test.rb
Bootstrap 4 wraps check boxes and radio buttons in a `div.form-check`. Similar to the `div.form-group` around other controls, this PR allows the programmer to add classes to the "wrapper" `div.form-check`, like we currently allow for the `div.form-group`.
This PR extends the `wrapper_class` option to `check_box` and `radio_button` helpers, and applies the classes to the `div.form-check` around the label and control for the check box or radio button. 
This PR also includes some refactoring in `check_box` and `radio_button`. The first commit shows the refactoring on `check_box`. The second adds the wrapper_class functionality. The third commit does the refactoring and adds the functionality on `radio_button`. (Sorry. I forgot the commit for the refactoring.) Finally, there is a commit to …
> Add classes to the `div.form-check` that wraps check boxes and radio buttons.

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_test.rb
Add add_control_col option on form_group.
This options allows caller to add classes on control col div, in addtion to the classes defined on the form.
> Add add_control_col option on form_group.

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
Add required option on form_group_builder :
= f.text_field :firstname, required: true
This option forces required class to be added, even if the there is no presence validation on the model.
This is usefull when the object model is not an active record model.
I will add tests and doc if you are interested
> add required option on form_group_builder

- README.md
I added example for changing default `label_col` and `control_col` since default `col-sm-2` and `col-sm-10` does not look good when I show the form in thin modal.
Please do not merge if this is against some best practices (maybe there is a better way of changing default values, instead reopening BoostrapForm::FormBuilder class).
> Add example for changing default value for label_col and control_col

- CHANGELOG.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_form_group_test.rb
Useful when real field value specified indirectly:
``` ruby
f.form_group :user do
f.email_field :email, wrapper: false
end
```
> Rendering input with bootstrap but without wrapper

- README.md
The wrapper option is added to the wrong options hash in the example.
> Fix code example for select

- Gemfile
- test/gemfiles/5.0.gemfile
- test/gemfiles/5.1.gemfile
- test/gemfiles/5.2.gemfile
- test/gemfiles/6.0.gemfile
Sqlite3 is at a new version, which breaks Rails somehow. This will probably be fixed in a later version, but for now we need to specify the sqlite3 version in our gemfiles. See: https://github.com/rails/rails/pull/35154.
> Fix TravisCI build for sqlite3 version change.

- .rubocop_todo.yml
- CHANGELOG.md
- README.md
- lib/bootstrap_form/inputs/check_box.rb
- test/bootstrap_fields_test.rb
Add :switch value to :custom option for 4.2 switches
> Add support for BS 4.2 switches

- bootstrap_form.gemspec
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_selects_test.rb
- test/test_helper.rb
Port the fix for #357 to the legacy 2.7 branch for Bootstrap 3 users.
This replaces PR #507, and fixes the Travis build issues due to newer gem versions breaking the build.
Thanks very much to @pinkahd for the original PR!
> Backport the id change to the legacy branch.

- CHANGELOG.md
- Dangerfile
- lib/bootstrap_form/form_group.rb
@lcreid I found a bug in my own code. This little fix allows help_text to be nil, and still work :|
> Only concat help_text if it exists

- README.md
- lib/bootstrap_form/action_view_extensions/form_helper.rb
- lib/bootstrap_form/components/layout.rb
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_radio_button_test.rb
Move `process_options` from helper since we can not override helper.
When someone wants to extend `BootstrapForm::FormBuilder` and use it in
`form_with .... builder: MyFormBuilder`, before this change he could not
use in this way since determination whether it is :inline :horizontal
was done in helper.
> Add `default_layout` so we can use it for all forms

- .rubocop.yml
- .travis.yml
- gemfiles/5.0.gemfile
- gemfiles/5.1.gemfile
- gemfiles/5.2.gemfile
- gemfiles/6.0.gemfile
- gemfiles/edge.gemfile
Travis uses about 40 seconds to install gems.  The goal is to reduce this as much as possible.
> Cache bundler to speed up travis build

- CHANGELOG.md
- README.md
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_group_test.rb
This is a feature we use in some of our apps.
I hope this can be merged and released.
Addresses #249
> Allow prepending and appending multiple items to an input

- CHANGELOG.md
- README.md
- bootstrap_form.gemspec
- lib/bootstrap_form.rb
- lib/bootstrap_form/configuration.rb
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_configuration_test.rb
- test/bootstrap_form_test.rb
This PR adds ability to configure `bootstrap_form` default form options
```ruby
BootstrapForm.configure do |c|
c.default_form_attributes = { something: "custom" }
end
```
Current default value is `{role: "form"}` which is not semantically correct as described in #560. In order to resolve original issue, `default_form_attributes` should be set to `{}`
```ruby
BootstrapForm.configure do |c|
c.default_form_attributes = {}
end
```
Closes #561
Closes #560
> Allow to configure default form attributes

- README.md
- demo/app/views/layouts/application.html.erb
- lib/bootstrap_form/components/labels.rb
- lib/bootstrap_form/form_builder.rb
- lib/bootstrap_form/form_group.rb
- lib/bootstrap_form/helpers/bootstrap.rb
- lib/bootstrap_form/inputs/base.rb
- lib/bootstrap_form/inputs/check_box.rb
- lib/bootstrap_form/inputs/collection_select.rb
- lib/bootstrap_form/inputs/file_field.rb
- lib/bootstrap_form/inputs/grouped_collection_select.rb
- lib/bootstrap_form/inputs/radio_button.rb
- lib/bootstrap_form/inputs/select.rb
- lib/bootstrap_form/inputs/time_zone_select.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_other_components_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_rich_text_area_test.rb
- test/bootstrap_selects_test.rb
- test/special_form_class_models_test.rb
With the Bootstrap 5 alpha out today, I thought I'd see how hard it would be to update the gem to support the latest alpha release.
This is a work-in-progress PR, but it does seem to be working, at least with the demo application forms. More work needs to be put into updating parts of the README.
I've also questionably removed some tests that I should probably look into figuring out if they're actually tests that should be removed, or slightly reworked.
One thing that might be worth discussing is Bootstrap 5's removal of the `.form-group` class. The concept is pretty hard-wired into the gem. Even though the class is gone, the "concept" of the form group wrapper is still there, just replaced with the `.mb-3` class to maintain the margin on the div. I don't think it would necessarily be a …
> Preliminary support for Bootstrap 5

- CHANGELOG.md
- README.md
- demo/app/views/bootstrap/form.html.erb
- lib/bootstrap_form/form_group.rb
- lib/bootstrap_form/form_group_builder.rb
- lib/bootstrap_form/inputs/base.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_selects_test.rb
Add support for Bootstrap 5 floating labels. See https://github.com/bootstrap-ruby/bootstrap_form/issues/573.
> Support Bootstrap 5 floating labels. Fixes #573

- CHANGELOG.md
- demo/app/assets/config/manifest.js
- demo/app/views/layouts/application.html.erb
- lib/bootstrap_form/inputs/file_field.rb
- test/bootstrap_fields_test.rb
Bootstrap 5 can now render a very nice looking file selector without needing additional classes or extra markup. This PR cleans up the generated HTML and tests. See https://github.com/bootstrap-ruby/bootstrap_form/issues/572.
At the same time, to get the demo app running, I've made these changes:
- remove the reference in manifest.js to the non existent folder `../images`
- update the Bootstrap 5 CDN links
> Simplify rendering of file_field for Bootstrap 5. Fixes #572

- .gitignore
- CONTRIBUTING.md
- Dockerfile
This PR makes the container generated by the `Dockerfile` meet the current version requirements for the minimum supported version of Ruby, and the version of Bundler than we've been using lately.
It also simplifies the `Dockerfile` and keeps everything under the directory in which you're developing. If your host is Linux, run the container as the current user, rather than the superuser. Instructions are in the `CONTRIBUTING.md` document.
> Simplify Dockerfile and add documentation

- .github/workflows/ruby.yml
- .gitignore
- .rubocop.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Dangerfile
- Dockerfile
- lib/bootstrap_form/helpers/bootstrap.rb
- lib/bootstrap_form/inputs/check_box.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_other_components_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_rich_text_area_test.rb
- test/bootstrap_selects_test.rb
- test/bootstrap_without_fields_test.rb
- test/special_form_class_models_test.rb
Fixes #585 for branch. The original intent was just merge `master` but it turned out to be messy. I hope I haven't included anything that shouldn't be here.
Review ignoring whitespace for optimum experience. (Click on the settings gear when you're looking at the "Files changed".)
> Get rid of `heredoc` on `bootstrap-5` branch

- .github/workflows/ruby.yml
- CONTRIBUTING.md
- Dockerfile
- README.md
- demo/app/assets/config/manifest.js
- demo/db/schema.rb
The demo app was no longer easy to run. This PR documents how to run it, and fixes the `Dockerfile` for those using it to run the demo app.
> Document How to Run Demo App

- .github/workflows/ruby.yml
- Dangerfile
- Gemfile
- bootstrap_form.gemspec
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_rich_text_area_test.rb
- test/bootstrap_selects_test.rb
Tests would no longer even start to run because `Rails.application.config.assets` was not available to set in `demo/config/initializers/assets.rb`. Adding gem `sassc-rails` makes the part of config available again.
Next rendering changed for hidden fields ('autocomplete="off"' was added) and rich text area.
Additionally a few Rubocop offences have been removed.
Fixes #609.
> Fix Rails Edge tests

- README.md
- lib/bootstrap_form/form_builder.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_radio_button_test.rb
https://getbootstrap.com/docs/5.0/migration/#helpers
> Update hide_class from sr-only to visually-hidden

- CONTRIBUTING.md
Fix a typo in `CONTRIBUTING.md`.
> Typo in Contributing Doc

- .gitignore
Add the various permutations of `gemfiles/x.y.gemfile.lock` to `.gitignore`. Perhaps when the test app got moved from `test/dummy` this wasn't updated.
Also don't check in whatever might be in the demo app's `vendor/bundle`. Some ways of using Docker might create the bundle in this location.
> Don't commit lockfiles or bundle

- .gitignore
- gemfiles/7.0.gemfile
CI has been failing due to an issue between Rails 7.0.0 and Ruby 3.1. Rails 7.0.1 fixes it.
> Rails 7.0.1

- CHANGELOG.md
- README.md
- lib/bootstrap_form/form_group.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_selects_test.rb
The wrapper now has a `mb-3` class by default which is correct by the Bootstrap 5 migration guide and documentation.  👍 
However, when you want to remove the bottom margin like some of the tests do, there should be a way to omit the `mb-3` class.  I think `wrapper_class: false`  should do this, so I'll add it to this PR.
Then, when you add classes, you should be able to add them to a clean slate.  That means that you need to include the `mb-3` class if you want it.
What do you think?
> Allow overriding the wrapper class

- CHANGELOG.md
- lib/bootstrap_form/inputs/collection_check_boxes.rb
- test/bootstrap_checkbox_test.rb
Fixes https://github.com/bootstrap-ruby/bootstrap_form/issues/215
Enable include_hidden option with collection_check_boxes:
> Enable include hidden

- lib/bootstrap_form/components/labels.rb
I'm not sure if it's like this intentionally, but the `human_attribute_name` was only used when there are errors.
> consider human attribute name for labels

- lib/bootstrap_form/components/hints.rb
Fixes #546 
Add Support for Ransack::Search object to the first argument of bootrap_form_for. 
Controller
```
def index
@q = Invoice.ransack(params[:q])
@invoices = @q.result(distinct: true)
end
```
View
```
= bootstrap_form_for @q, url: invoices_path, method: :get do |f|
= f.search_field :file_name_cont
= f.submit
```
> Add support for Ransack::Search object to the first argument of bootrap_form_for

- README.md
- demo/test/system/bootstrap_test.rb
This just updates the documented trix editor example with new generated HTML.
The main difference in the generated HTML is the addition of the `trix-toolbar` tag.
> Update the generated HTML for the trix editor example

- demo/test/system/bootstrap_test.rb
- lib/bootstrap_form/inputs/collection_select.rb
- lib/bootstrap_form/inputs/grouped_collection_select.rb
- test/bootstrap_selects_test.rb
Hello,
thanks a lot for creating this gem! 
Today I would have needed a `collection_select` with `prepend` and noticed that this does not work yet.
Here's a fix for it. I hope everything's alright and would be happy if it got merged :slightly_smiling_face: 
Best,
Judith
> Add support for append and prepend on collection_select (fixes #428)

- gemfiles/7.0.gemfile
I got confused by test failures when all that was missing was the fact that a test for Rails 7 requires 7.0.2 at least.
> Need 7.0.2 for file upload test

- .gitignore
- Dockerfile
- docker-compose.yml
Experimental support for a docker container that can be used to release the gem (has support for enough networking to use ssh).
> Use docker-compose

- CONTRIBUTING.md
- docker-compose.yml
Removed some of the Linux-specific config from `docker-compose.yml`, and improved the documentation showing `docker-compose.override.yml` that exposes the host's credentials in the container, so you can release the gem from within the Docker container.
> More portable `docker-compose.yml` and better documentation

- test/bootstrap_fields_test.rb
https://discuss.rubyonrails.org/t/cve-2022-32224-possible-rce-escalation-bug-with-serialized-columns-in-active-record/81017 prevents serialization of a `Symbol` because it's potentially a security vulnerability. This PR changes a test so it serializes and attribute value with a `String` key rather than a `Symbol`.
> CVE fix breaks serialization of symbols -- fix test

- Gemfile
- bootstrap_form.gemspec
- gemfiles/5.2.gemfile
- gemfiles/6.0.gemfile
- gemfiles/6.1.gemfile
- gemfiles/7.0.gemfile
- gemfiles/common.gemfile
- gemfiles/edge.gemfile
- lib/bootstrap_form/version.rb
Now `bundle exec rake` works out of the box.
> This allows running tests on the root of the project freshly checked out

- gemfiles/common.gemfile
- test/test_helper.rb
Adding `debug` and `pry-byebug` to the `:development, :test` group in the `common.gemfile`. `pry-byebug` should allow the use of either `binding.pry` or `byebug`, whichever you prefer.
Also adding `puma` to the `:dev` group, so the demo app runs under Puma.
> Add Puma and Debuggers to common.gemfile

- .github/workflows/ruby.yml
- .rubocop.yml
- test/test_helper.rb
It looks like a recent update to Rubocop rules means that we can't apply the latest Rails rules on the earliest Rails version we support. This PR adds an explicit Rails version to the `rubocop.yml` file.
> Lint on oldest Rails version

- test/test_helper.rb
I've been fighting with Rubocop and realized that the suggestion/autocorrect is simply wrong, because the method isn't a method on `Date` or `Time`.
> Fix the bogus Rubocop Autocorrect

- lib/bootstrap_form/components/labels.rb
- lib/bootstrap_form/components/validation.rb
- lib/bootstrap_form/form_group.rb
- lib/bootstrap_form/helpers/bootstrap.rb
- lib/bootstrap_form/inputs/check_box.rb
- lib/bootstrap_form/inputs/radio_button.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
`ActionView::Helpers::TextHelper#concat` is [not recommended](https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-concat) for use, and was leading to some confusing results while I was trying to refactor for #642 . 
This PR removes `concat` from the code, except where it was needed in some test cases. (And perhaps there's a way to get rid of it from the test cases, too, but I didn't investigated it.) In the test cases, we now use `ActionView::Helpers::TextHelper#concat` consistently.
This PR also replaces `String#+=` with `String#<<` since the internet says the `String#<<` is much faster.
> Don't use `concat` when not necessary

- lib/bootstrap_form/components/labels.rb
- lib/bootstrap_form/form_builder.rb
- lib/bootstrap_form/form_group_builder.rb
- lib/bootstrap_form/helpers.rb
- lib/bootstrap_form/helpers/bootstrap.rb
- lib/bootstrap_form/helpers/field.rb
- lib/bootstrap_form/inputs/check_box.rb
- lib/bootstrap_form/inputs/radio_button.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_other_components_test.rb
- test/bootstrap_radio_button_test.rb
https://github.com/bootstrap-ruby/bootstrap_form/issues/663
> Set required and aria-required on the input when the input is required

- Rakefile
Minitest has a test runner. I have no idea how long it's been available, or why we weren't using it before. It offers a few options that I don't think we had before, when running `rake test`. They're described [here](https://github.com/minitest/minitest#rake-task-variables-).
> Use the minitest test runner

- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_other_components_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_rich_text_area_test.rb
- test/bootstrap_selects_test.rb
If we're going to do major work/refactoring, I think we need to make sure we preserve the behaviour of arguments that _are not_ processed by `bootstrap_form`. This PR adds an extra arg to a few tests, which should cover variations of at least the current implementation.
> Test extra arguments

- .github/workflows/ruby.yml
- CONTRIBUTING.md
- demo/app/models/user.rb
- gemfiles/edge.gemfile
- lib/bootstrap_form.rb
- lib/bootstrap_form/helpers/bootstrap.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_rich_text_area_test.rb
- test/test_helper.rb
A number of changes to Rails in Edge or recent versions, and RuboCop:
- Error messages use a curly apostrophe.
- `ActiveRecord::AttributeMethods::Serialization::ClassMethods#serialize` starts requiring a keyword argument for the serializer class.
- `master` no longer seems to be a branch alias in Rails.
- New RuboCop offenses.
> CI Updates

- test/bootstrap_fields_test.rb
It wasn't clear what should happen if both `wrapper_class: ...` and `wrapper: { class: ...` were specified. These tests show that `wrapper: { class: ...` wins.
> Test wrapper_class and wrapper: { class: specified

- test/bootstrap_fields_test.rb
- test/bootstrap_form_test.rb
Some tests were only run for versions of Rails that we're no longer testing against. This PR removes them. Some tests were only run for versions 5.2 and greater. This PR removes the conditionals around those tests, since we don't test against those older versions anymore.
> Remove tests for versions before 5.2

- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_other_components_test.rb
- test/bootstrap_radio_button_test.rb
- test/bootstrap_rich_text_area_test.rb
- test/bootstrap_selects_test.rb
- test/bootstrap_without_fields_test.rb
- test/special_form_class_models_test.rb
- test/test_helper.rb
In working on a new implementation, it began to look like tests were passing when they shouldn't have passed. I made a branch off `main` and confirmed that we weren't testing the order of elements, which is significant in HTML.
Once that was fixed, it turned out that our code for handling some of the variations was also passing tests that it shouldn't have been passing. A couple of more changes fixed that.
Finally, three tests were failing because the expected strings were incorrect, but the other issues mentioned above were hiding that the tests should have failed.
In the process of fixing, we changed to use Nokogiri's HTML instead of XML. And to make it clear, the assertion helper was changed in all the test files.
Fixes: #674
> 674 html tests

- README.md
- lib/bootstrap_form/inputs/inputs_collection.rb
- test/bootstrap_checkbox_test.rb
Hi, I need the capability to add `data-` HTML attributes to collections of radio buttons. If found that this works, it may or may not be implemented the way you'd like - so I'm happy to fix/change whatever you ask (this PR is editable by maintainers). 
Just a little more information here, you can see from the tests I'm adding `data-city` attributes to each input tag.
```html
<input class="form-check-input" data-city="east" id="user_misc_1" name="user[misc][]" type="checkbox" value="1" />
```
We pass in `Array`s using `:first` and `:second`  for value and label functions respectively. One element, the `Hash`, is all the extra HTML `data-` attributes we'd like to add.
```ruby
['1', 'Foo', {'data-city': 'east'} ],
```
> allow for data- attributes to pass through for radio button collections

- README.md
- lib/bootstrap_form/helpers/field.rb
- test/bootstrap_checkbox_test.rb
- test/bootstrap_fields_test.rb
- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/bootstrap_other_components_test.rb
- test/bootstrap_radio_button_test.rb
- test/special_form_class_models_test.rb
Per the MDN docs, the aria-required attribute is only necessary on non-semantic elements. The `input` element is a semantic element and so aria-required is not necessary -- just `required` is sufficient and achieves the same result. An example of a non-semantic element is `div` which is not used by the project.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-required
> When a semantic HTML <input>, <select>, or <textarea> must have a
> value, it should have the required attribute applied to it.
>
> ...
>
> When form controls are created using non-semantic elements, such as a
> <div> with a role of checkbox, the aria-required attribute should be
> included, with a value of true, to indicate to assistive technologies
> that user input is required on the …
> Remove aria-required attribute from semantic element `input`

- README.md
This PR fixes the issue of broken section links in the README.md file. The following section links have been corrected for accurate navigation:
- bootstrap_form_with
- bootstrap_form_for
- bootstrap_form_tag
> Fix broken section links in README.md [ci skip]

- lib/bootstrap_form/components/labels.rb
- lib/bootstrap_form/components/validation.rb
- lib/bootstrap_form/form_builder.rb
- lib/bootstrap_form/form_group_builder.rb
- lib/bootstrap_form/helpers/bootstrap.rb
- lib/bootstrap_form/inputs/rich_text_area.rb
The basic `String#join` makes its output unsafe in all cases. This might have been causing unwanted and problematic escaping in some cases. This PR removes the use of `String#join`. It _should_ still escape unsafe strings passed in from the calling code, while not escaping anything that is already safe. However, that's something reviewers should put some thoughts into, and comment on.
This PR may cause some text to be escaped that wasn't previously escaped, but those cases would have been potentially security vulnerabilities, so I think it's justifiable in closing that possible loophole. The fix would be for the calling code to pass its string as `string.html_safe` if the code is confident the string is safe (i.e. it doesn't come from the user or the database or something external). If …
> Fix joins not to make strings unsafe

- test/bootstrap_form_group_test.rb
- test/bootstrap_form_test.rb
- test/special_form_class_models_test.rb
- test/test_helper.rb
Rails has reverted the proposed change to put a "smart apostrophe" in error messages, so test cases against edge were failing. This PR removes the conditionals that were added for testing against edge/7.1.
https://github.com/rails/rails/commit/acfa0454058c535c1352ddab91c93ca914f0805a
> Revert to simple ' in error messages

- .gitignore
- CONTRIBUTING.md
- demo/Procfile.dev
- demo/test/application_system_test_case.rb
- docker-compose-system-test.yml
@donv very nicely added system tests that generate screenshots for the `README`. This PR adds support to the optional Docker and Docker Compose files so that the system tests can be run in Docker.
The intent is to ensure that system tests can still be run without Docker, but that they will also run for those who prefer to develop in a Docker environment, because they want to isolate their development work, or for whatever other reason.
This PR introduces a new Docker Compose file: `docker-compose-system-test.yml`. This file uses a standard Selenium image for Chrome to run the browser. Part of the reason for a separate file is the current `docker-compose.yml` results in smaller containers, since it doesn't have the full browser. I also wanted to try things in a completely separate file, to …
> Dockerize System Tests

- .rubocop.yml
- lib/bootstrap_form/inputs/base.rb
- lib/bootstrap_form/inputs/rich_text_area.rb
We experienced an error with eager loading in staging for bootstrap_form. This small if statement resolves that issue.
> do not alias rich text area if it is not defined

- lib/bootstrap_form.rb
This require was added in e6f5b09209147143ebdb83032a50e9758cfdc2ab to add ActionText support.
Instead of eagerly loading the module, allow the Rails engine subsystem to load the helpers as necessary.
Eagerly loading the module has the downside of defining the module ActionText even when the engine is not in use. Defining the module like this can "trick" other gems into erroneously loading their ActionText support, which may lead to confusing and out of context error messages.
Fixes #719
> Remove the require expression for action text in lib/bootstrap_form.rb

- README.md
Since switching the stylesheet to plain CSS, the import for SCSS projects now needs to include the file extension to work correctly.
[ci skip]
> Add file extension to import documentation

- lib/bootstrap_form/inputs/collection_check_boxes.rb
- test/bootstrap_checkbox_test.rb
In response to #717 . Is this what we needed to maintain Rails 6.1 compatibility with the Rails 7.1 `field_name` method?
Feel free to ignore this PR, or take it over and fix it.
> Draft PR Is This What We Meant To Do?

- Gemfile
- demo/Gemfile
- demo/Gemfile.lock
- gemfiles/7.1.gemfile
- gemfiles/edge.gemfile
The bug in `sprockets-rails` 3.5.0 was fixed so 3.5.1 and beyond should be okay.
> Relax sprockets rails

- lib/bootstrap_form/inputs/base.rb
- test/bootstrap_fields_test.rb
> Fix: Add missing form-control-color class for color_field

- .github/workflows/ruby.yml
- Rakefile
- gemfiles/8.0.gemfile
- lib/bootstrap_form/inputs/check_box.rb
Like the title says, catch up to the current Rails version in both tests and the demo app.
> Test Rails 8.0 and Upgrade Demo App to 8.0

- Gemfile
- demo/app/models/user.rb
- lib/bootstrap_form/inputs/collection_check_boxes.rb
- lib/bootstrap_form/inputs/file_field.rb
- test/bootstrap_form_group_test.rb
The file input appears to be treated like any of the other input types in Bootstrap 5. This branch simply removes the previous behavior of forcing it to be wrapped in `input_with_error`, which does not allow options, and instead uses `prepend_and_append_input`, which does. This is the same pattern used in the text input, for example. Errors are handled inside of the `prepend_and_append_input` method, so there's no loss of proper feedback after an invalid submit.
> Allow file to be -pended

- .devcontainer.json
- .yarnrc
- CONTRIBUTING.md
- DOCKER.md
- Gemfile
- compose.yml
A few changes to make Docker development better.
- Use ephemeral ports. The downside is you have to figure out what the ports are. I added it to the documentation.
- A few other documentation updates.
- Move `devcontainer.json`.
- [Not Docker] Fix the default `Gemfile` for the oldest Rails version (currently 7.1).
> Docker use ephemeral ports

- CONTRIBUTING.md
- README.md
Further documentation improvements for installation.
> Explain installation for modern Rails
